name: leafy_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ">=3.5.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Firebase dependencies
  firebase_core: ^3.7.0        
  firebase_storage: ^12.3.4    
  firebase_database: ^11.1.4   
  firebase_auth: ^5.3.1        
  cloud_firestore: ^5.4.4       

  # Otras dependencias
  flex_color_scheme: ^7.3.1    
  image_picker: ^1.1.2          
  backdrop: ^0.9.1              
  smooth_page_indicator: ^1.0.0 
  shared_preferences: ^2.0.15   

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0        

flutter:
  uses-material-design: true

  # Activos (imágenes y fuentes)
  assets:
    - lib/assets/images/playstore.png
    - lib/assets/images/Arapanto.jpeg
    - lib/assets/images/fertilizante.png
    - lib/assets/images/usuario.jpeg
    - lib/assets/images/whats.png

  fonts:
    - family: AcafadFlux-Regular 
      fonts:
        - asset: lib/assets/fonts/AfacadFlux-Regular.ttf
